<head>
  <title>Ubettor - Bet Now!</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="/PlayerInteraction/BOSSAuthentication2024-10/ubettor/styles.css" />
  <link rel="icon" type="image/png" sizes="32x32" href="/PlayerInteraction/BOSSAuthentication2024-10/ubettor/images/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/PlayerInteraction/BOSSAuthentication2024-10/ubettor/images/favicon-16x16.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/PlayerInteraction/BOSSAuthentication2024-10/ubettor/images/apple-touch-icon.png">

